name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
   ### Firebase
  # For Firebase initialization. -> https://pub.dev/packages/firebase_core
  firebase_core: ^3.10.0
  # For storing storing nfc tag details. -> https://pub.dev/packages/firebase_database
  firebase_database: ^11.3.0
  # For storing item data in Firestore. -> https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^5.6.1 
  # For Authentication. -> https://pub.dev/packages/firebase_auth
  firebase_auth: ^5.4.0
  # For storing images. -> https://pub.dev/packages/firebase_storage
  firebase_storage: ^12.4.0
  firebase_remote_config: ^5.3.0
  cloud_functions: ^5.3.1
  # for easy debugging -> https://pub.dev/packages/logger
  logger: ^2.3.0
  # navigation
  # for navigation -> https://pub.dev/packages/go_router
  go_router: ^14.3.0
  # UI related packages
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #  https://pub.dev/packages/gap
  gap: ^3.0.1
  # for toast messages -> https://pub.dev/packages/toastification
  toastification: ^2.3.0
  # for skeleton loading -> https://pub.dev/packages/skeletonizer

  # https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1
  # for lottie animations -> https://pub.dev/packages/lottie

  # for markdown support -> https://pub.dev/packages/flutter_markdown 
  flutter_markdown: ^0.7.3+2
  flutter_svg: ^2.0.16
  easy_localization: ^3.0.7

   # for camera usage  -> https://pub.dev/packages/image_picker
  # for image caching -> https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1
  # for localizations -> https://pub.dev/packages/easy_localization
  email_validator: ^3.0.0
  json_annotation:
  uuid: ^4.5.1
  url_launcher: ^6.3.1

  flutter_animate: ^4.5.2
  easy_sidemenu: ^0.6.0
  syncfusion_flutter_datagrid: ^28.1.41
  syncfusion_flutter_core: ^28.1.41
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  very_good_analysis: ^7.0.0
  flutter_lints: ^5.0.0




flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
